### PR TITLE
Pass environment to resolve function

### PR DESCRIPTION
**Pull request by hungneox**
screen shot 2018-03-08 at 4 27 36

@crisu83 I'm not sure if this is an expected behaviour or not but I think there should be `name` argument?

### CODE REVIEW

**Comment by crisu83** [comment]
@Jalle19 Phpstan is failing all of our builds, can we drop the level back to 1?

**Comment by crisu83** [comment]
@hungneox Arguments are lazy so the arguments should be under `$config` until it's actually invoked throught `getArguments`. Was this ok is there still an issue with this?

**Comment by crisu83** [comment]
Rebased on *master*.

**Comment by Jalle19** [comment]
Maybe we could add StyleCI to this project?

**Pull request merged**
