### PR TITLE
Upgrade phpstan and add config file

### PR DESCRIPTION
**Pull request by symm**
Upgrades phpstan and moves settings into a config file.

The latest version of phpstan has some new checks which have highlighted a few issues (mostly around casting to string and making league/container specific calls)

### CODE REVIEW

**Comment by Jalle19** [comment]
That is a lot of errors. @crisu83 how should we go about fixing these?

**Comment by crisu83** [comment]
@Jalle19 I can take a look at this at some point.

**Comment by Jalle19** [comment]
Made an issue upstream about those container type-hint issues: https://github.com/thephpleague/container/issues/159

**Comment by Jalle19** [comment]
Closing in favor of https://github.com/digiaonline/graphql-php/pull/338

**Pull request closed without merging**
